INSERT INTO City VALUES('Alta Floresta dOeste')
INSERT INTO City VALUES('Alto Alegre do Parecis')
INSERT INTO City VALUES('Alto Paraiso')
INSERT INTO City VALUES('Alvorada dOeste')
INSERT INTO City VALUES('Ariquemes')
INSERT INTO City VALUES('Buritis')
INSERT INTO City VALUES('Cabixi')
INSERT INTO City VALUES('Cacaulandia')
INSERT INTO City VALUES('Cacoal')
INSERT INTO City VALUES('Campo Novo de Rondonia')
INSERT INTO City VALUES('Candeias do Jamari')
INSERT INTO City VALUES('Castanheiras')
INSERT INTO City VALUES('Cerejeiras')
INSERT INTO City VALUES('Chupinguaia')
INSERT INTO City VALUES('Colorado do Oeste')
INSERT INTO City VALUES('Corumbiara')
INSERT INTO City VALUES('Costa Marques')
INSERT INTO City VALUES('Cujubim')
INSERT INTO City VALUES('Espigao dOeste')
INSERT INTO City VALUES('Governador Jorge Teixeira')
INSERT INTO City VALUES('Guajara-Mirim')
INSERT INTO City VALUES('Jamari')
INSERT INTO City VALUES('Jaru')
INSERT INTO City VALUES('Ji-Parana')
INSERT INTO City VALUES('Machadinho dOeste')
INSERT INTO City VALUES('Ministro Andreazza')
INSERT INTO City VALUES('Mirante da Serra')
INSERT INTO City VALUES('Monte Negro')
INSERT INTO City VALUES('Nova Brasilandia dOeste')
INSERT INTO City VALUES('Nova Mamore')
INSERT INTO City VALUES('Nova Uniao')
INSERT INTO City VALUES('Novo Horizonte do Oeste')
--INSERT INTO City VALUES('Ouro Preto do Oeste')
INSERT INTO City VALUES('Parecis')
INSERT INTO City VALUES('Pimenta Bueno')
INSERT INTO City VALUES('Pimenteiras do Oeste')
--INSERT INTO City VALUES('Porto Velho')
INSERT INTO City VALUES('Presidente Medici')
INSERT INTO City VALUES('Primavera de Rondonia')
INSERT INTO City VALUES('Rio Crespo')
INSERT INTO City VALUES('Rolim de Moura')
INSERT INTO City VALUES('Santa Luzia dOeste')
INSERT INTO City VALUES('Sao Felipe dOeste')
INSERT INTO City VALUES('Sao Francisco do Guapore')
INSERT INTO City VALUES('Sao Miguel do Guapore')
INSERT INTO City VALUES('Seringueiras')
INSERT INTO City VALUES('Teixeiropolis')
INSERT INTO City VALUES('Theobroma')
INSERT INTO City VALUES('Urupa')
INSERT INTO City VALUES('Vale do Anari')
INSERT INTO City VALUES('Vale do Paraiso')
INSERT INTO City VALUES('Vilhena')